MDlogger/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.contrib import admin
from .views import data, dashboard, projects, metrics, add_repair, sku_entry, lp_entry, associate_home, logout_request, index, mark_project_complete

app_name = 'MDlogger'
urlpatterns = [
    path ('', views.index, name='index'),
    path ('admin/', admin.site.urls, name='admin'),
    path ('logout', views.logout_request, name='logout'),
    path ('associate_home', views.associate_home, name='associate_home'),
    path('mark_project_complete/<int:project_id>/', mark_project_complete, name='project_complete'),
    path ('lp_entry', views.lp_entry, name='lp_entry'),
    path ('sku_entry', views.sku_entry, name='sku_entry'),
    path ('add_repair', views.add_repair, name='add_repair'),
    path ('metrics', views.metrics, name='metrics'),
    path ('data', views.data, name='data'),
    path ('dashboard', views.dashboard, name='dashboard'),
    path ('projects', views.projects, name='projects'),
    
 ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MajorDamage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('MDlogger/', include('MDlogger.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MDlogger/models.py
from django.contrib.auth.models import User
from django.db import models


class SavedRepair(models.Model):
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    sku = models.IntegerField()
    lp = models.CharField(max_length=255)
    repair = models.TextField()


    def __str__(self):
        return f"{self.date} {self.time} - {self.user.first_name} {self.user.last_name} - SKU: {self.sku}, LP: {self.lp}"  
    
class Projects(models.Model):
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    assignedto = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='assigned_projects')
    due = models.DateField()
    department = models.CharField(max_length=80)
    project = models.CharField(max_length=200)
    description = models.TextField()
    STATUS_CHOICES = [
        ('Incomplete', 'Incomplete'),
        ('Completed', 'Completed'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Incomplete')

    def __str__(self):
        return f"{self.date} {self.time} - {self.user.first_name} {self.user.last_name} - {self.project} - {self.description} - {self.status}"

MDlogger/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib import messages
from datetime import datetime, timedelta, date
from .models import SavedRepair, Projects
from .forms import AddRepairForm, ProjectsForm
import pandas as pd
import xlsxwriter
from django.db.models import Q
from django.http import JsonResponse
from django import forms
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect







def index(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('MDlogger:index')
    else:
        form = AuthenticationForm()
    return render(request, 'MDlogger/index.html', {'form': form})

def logout_request(request):
    logout(request)
    return render(request, 'MDlogger/logout.html')

def associate_home(request):
    current_date = datetime.now().date()
    repairs = SavedRepair.objects.filter(user=request.user, date=current_date).order_by('-date', '-time')
    pieces_repaired_today = len(repairs)

    projects = Projects.objects.filter(user=request.user, date=current_date, assignedto = request.user, status="Incomplete").order_by('-date')


    return render(request, 'MDlogger/associate_home.html', {'repairs': repairs,'pieces_repaired_today': pieces_repaired_today , 'projects': projects})

def mark_project_complete(request, project_id):
    project = get_object_or_404(Projects, id=project_id)

    # Update the status of the project to 'Complete' (or your desired status)
    project.status = 'Completed'
    project.save()

    # Redirect back to the home page or any other desired page
    return HttpResponseRedirect(reverse('MDlogger:associate_home'))

def lp_entry(request):
    lp = None
    previous_repairs = None

    if request.method == "POST":
        lp = request.POST.get('lp') 
        if SavedRepair.objects.filter(lp=lp, date=datetime.now().date()).exists():

            previous_repairs = SavedRepair.objects.filter(lp=lp, date=datetime.now().date())
        else:
            request.session['lp'] = lp
            return redirect('MDlogger:sku_entry')

    return render(request, 'MDlogger/lp_entry.html', {'lp': lp, 'previous_repairs': previous_repairs})

def sku_entry(request):
    lp = request.session.get('lp')
    if lp is None:
        return redirect('MDlogger:associate_home')
    if request.method == "POST":
        sku = request.POST.get('sku')
        request.session['sku'] = sku
        return redirect('MDlogger:add_repair')
    return render(request, 'MDlogger/sku_entry.html', {'lp': lp})
    

def add_repair(request):
    lp = request.session.get('lp')
    sku = request.session.get('sku')
    
    if lp is None or sku is None:
        return redirect('MDlogger:associate_home')

    form = AddRepairForm()  # Instantiate the form outside the if block

    if request.method == "POST":
        form = AddRepairForm(request.POST)

        if form.is_valid():
            date = datetime.now()
            time = request.POST.get('time')
            user_first_name = request.user.first_name
            user_last_name = request.user.last_name
            repair = form.cleaned_data['repair']
            SavedRepair.objects.create(
                date=date,
                time=time,
                user=request.user,
                sku=sku,
                lp=lp,
                repair=repair
            )
            messages.success(request, f"Repair for LP {lp} saved.")
            return redirect('MDlogger:associate_home')
    
    return render(request, 'MDlogger/add_repair.html', {'form': form, 'sku': sku, 'lp': lp})

def metrics(request):  
    return render(request, 'MDlogger/metrics.html')



def data(request):
    sort_by = request.GET.get('sort_by', 'date')
    start_date_param = request.GET.get('start_date')
    end_date_param = request.GET.get('end_date')

    ninety_days_ago = datetime.now() - timedelta(days=90)
    start_date_default = ninety_days_ago.replace(hour=0, minute=0, second=0)
    end_date_default = datetime.now().replace(hour=23, minute=59, second=59)

    start_date = datetime.strptime(start_date_param, "%Y-%m-%d") if start_date_param else start_date_default
    end_date = datetime.strptime(end_date_param, "%Y-%m-%d") if end_date_param else end_date_default

    repairs = SavedRepair.objects.all()

    if start_date and end_date:
        repairs = repairs.filter(date__range=(start_date, end_date))

    repairs = repairs.order_by(sort_by)

    # Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(repairs, 10)  # Show 10 repairs per page
    try:
        repairs = paginator.page(page)
    except PageNotAnInteger:
        repairs = paginator.page(1)
    except EmptyPage:
        repairs = paginator.page(paginator.num_pages)

    context = {
        'repairs': repairs,
        'paginator': paginator,
    }

    export_to_excel = request.GET.get('export_to_excel')
    if export_to_excel:
        # Retrieve the entire filtered list for export
        all_repairs = SavedRepair.objects.filter(date__range=(start_date, end_date)).order_by(sort_by)
        df = pd.DataFrame(list(all_repairs.values_list()), columns=['Repair ID','Date', 'Time', 'User', 'SKU', 'LP', 'Repair'])
        df['Time'] = df['Time'].apply(lambda x: x.strftime("%I:%M %p"))
        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'attachment; filename=repairs_data.xlsx'
        column_widths = {'A': 12, 'B': 15, 'C': 22, 'D': 15, 'E': 15, 'F': 30, 'G': 50}  # Adjust widths as needed

        with pd.ExcelWriter(response, engine='xlsxwriter') as writer:
            df.to_excel(writer, index=False, sheet_name='Sheet1')

            # Access the XlsxWriter workbook and worksheet objects
            workbook = writer.book
            worksheet = writer.sheets['Sheet1']

            # Apply the specified column widths
            for col, width in column_widths.items():
                worksheet.set_column(col + ':' + col, width)
        cell_format = workbook.add_format({'align': 'center'})
        worksheet.set_column('A:G', cell_format)
        return response
    return render(request, 'MDlogger/data.html', context)





def format_time_range(start_time, end_time):
    # Format the time range in AM/PM format
    formatted_start_time = datetime.strptime(start_time, "%H:%M").strftime("%I:%M %p")
    formatted_end_time = datetime.strptime(end_time, "%H:%M").strftime("%I:%M %p")
    return f"{formatted_start_time} - {formatted_end_time}"

def dashboard(request):
    current_date = datetime.today().date()
    time_ranges = [
        {'start': '06:00', 'end': '06:59'},
        {'start': '07:00', 'end': '07:59'},
        {'start': '08:00', 'end': '08:59'},
        {'start': '09:00', 'end': '09:59'},
        {'start': '10:00', 'end': '10:59'},
        {'start': '11:00', 'end': '11:59'},
        {'start': '12:00', 'end': '12:59'},
        {'start': '13:00', 'end': '13:59'},
        {'start': '14:00', 'end': '14:59'},
        {'start': '15:00', 'end': '15:59'},
        {'start': '16:00', 'end': '16:59'},
        {'start': '17:00', 'end': '17:59'},
        {'start': '18:00', 'end': '18:59'},
        {'start': '19:00', 'end': '19:59'},
        {'start': '20:00', 'end': '20:59'},
        {'start': '21:00', 'end': '21:59'},
        {'start': '22:00', 'end': '22:59'},
        {'start': '23:00', 'end': '23:59'},
        # Add more time ranges as needed
    ]

    # Initialize a list to store data for each time range
    dashboard_data = []

    for time_range in time_ranges:
        start_time = time_range['start']
        end_time = time_range['end']

        # Filter SavedRepair objects for the current date and time range
        repairs_in_range = SavedRepair.objects.filter(
            date=current_date,
            time__gte=start_time,
            time__lte=end_time
        )
         # Count the number of repairs in the current time range
        pieces_repaired = repairs_in_range.count()
        formatted_time_range = format_time_range(start_time, end_time)

        dashboard_data.append({
            'time_range': formatted_time_range,
            'pieces_repaired': pieces_repaired,
        })

    # Append total row to the dashboard_data list
    dashboard_data.append({
        'time_range': 'Total:',
        'pieces_repaired': 0,  # Placeholder, as it will be updated in JavaScript
    })

    # Update the DataFrame with the total row
    dashboard_df = pd.DataFrame(dashboard_data)

    return render(request, 'MDlogger/dashboard.html', {'dashboard_df': dashboard_df})


def projects(request):
    projects = Projects.objects.all()



    form = ProjectsForm()  # Instantiate the form outside the if block
    if request.method == 'POST':
        form = ProjectsForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.user = request.user
            project.save()
            return redirect('MDlogger:projects')
              # Redirect to the project list page after successful form submission
    else:
        form = ProjectsForm()

    
    return render(request, 'MDlogger/projects.html', {'projects': projects, 'form': form})

MDlogger/views/add_repair.py
from django.shortcuts import redirect, render
from django.contrib import messages
from datetime import datetime
from ..models import SavedRepair
from ..forms import AddRepairForm

def add_repair(request):
    lp = request.session.get('lp')
    sku = request.session.get('sku')
    
    if lp is None or sku is None:
        return redirect('MDlogger:associate_home')

    form = AddRepairForm() 

    if request.method == "POST":
        form = AddRepairForm(request.POST)

        if form.is_valid():
            date = datetime.now()
            time = request.POST.get('time')
            user_first_name = request.user.first_name
            user_last_name = request.user.last_name
            repair = form.cleaned_data['repair']
            SavedRepair.objects.create(
                date=date,
                time=time,
                user=request.user,
                sku=sku,
                lp=lp,
                repair=repair
            )
            messages.success(request, f"Repair for LP {lp} saved.")
            return redirect('MDlogger:associate_home')
    
    return render(request, 'MDlogger/add_repair.html', {'form': form, 'sku': sku, 'lp': lp})

MDlogger/views/associate_home.py
from django.shortcuts import render
from datetime import datetime
from ..models import SavedRepair, Projects

def associate_home(request):
    current_date = datetime.now().date()
    repairs = SavedRepair.objects.filter(user=request.user, date=current_date).select_related('user').order_by('-date', '-time')
    pieces_repaired_today = repairs.count()
    projects = Projects.objects.filter(date=current_date, assignedto = request.user, status="Incomplete").order_by('-date')
    return render(request, 'MDlogger/associate_home.html', {'repairs': repairs,'pieces_repaired_today': pieces_repaired_today , 'projects': projects})

MDlogger/views/dashboard.py
from django.shortcuts import render
from django.shortcuts import redirect, render
from datetime import datetime, timedelta, date
from ..models import SavedRepair, Projects
import pandas as pd

def format_time_range(start_time, end_time):
    formatted_start_time = datetime.strptime(start_time, "%H:%M").strftime("%I:%M %p")
    formatted_end_time = datetime.strptime(end_time, "%H:%M").strftime("%I:%M %p")
    return f"{formatted_start_time} - {formatted_end_time}"

def dashboard(request):
    current_date = datetime.today().date()
    time_ranges = [
        {'start': '06:00', 'end': '06:59'},
        {'start': '07:00', 'end': '07:59'},
        {'start': '08:00', 'end': '08:59'},
        {'start': '09:00', 'end': '09:59'},
        {'start': '10:00', 'end': '10:59'},
        {'start': '11:00', 'end': '11:59'},
        {'start': '12:00', 'end': '12:59'},
        {'start': '13:00', 'end': '13:59'},
        {'start': '14:00', 'end': '14:59'},
        {'start': '15:00', 'end': '15:59'},
        {'start': '16:00', 'end': '16:59'},
        {'start': '17:00', 'end': '17:59'},
        {'start': '18:00', 'end': '18:59'},
        {'start': '19:00', 'end': '19:59'},
        {'start': '20:00', 'end': '20:59'},
        {'start': '21:00', 'end': '21:59'},
        {'start': '22:00', 'end': '22:59'},
        {'start': '23:00', 'end': '23:59'},
    ]

    dashboard_data = []

    for time_range in time_ranges:
        start_time = time_range['start']
        end_time = time_range['end']
        repairs_in_range = SavedRepair.objects.filter(
            date=current_date,
            time__gte=start_time,
            time__lte=end_time
        )
         # Count the number of repairs in the current time range
        pieces_repaired = repairs_in_range.count()
        formatted_time_range = format_time_range(start_time, end_time)

        dashboard_data.append({
            'time_range': formatted_time_range,
            'pieces_repaired': pieces_repaired,
        })

    dashboard_data.append({
        'time_range': 'Total:',
        'pieces_repaired': 0,
    })

    dashboard_df = pd.DataFrame(dashboard_data)

    return render(request, 'MDlogger/dashboard.html', {'dashboard_df': dashboard_df})

MDlogger/views/index.py
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.shortcuts import redirect, render

def index(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('MDlogger:index')
    else:
        form = AuthenticationForm()
    return render(request, 'MDlogger/index.html', {'form': form})

MDlogger/views/logout.py
from django.shortcuts import render
from django.contrib.auth import logout

def logout_request(request):
    logout(request)
    return render(request, 'MDlogger/logout.html')

MDlogger/views/mark_project_complete.py
from ..models import Projects
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect

def mark_project_complete(request, project_id):
    project = get_object_or_404(Projects, id=project_id)
    project.status = 'Completed'
    project.save()
    return HttpResponseRedirect(reverse('MDlogger:associate_home'))

MDlogger/templates/MDlogger/add_repair.html
{% extends 'MDlogger/base.html' %}

{% block content %}
<style>
    /* Additional styles for the Add Repair form */
    .add-repair-form {
        display: flex;
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
    }

    #form-container {
        flex: 1;
        max-width: 600px;
        margin-right: 20px;
        
    }

    #iframe-container {
        flex: 2;
        border: solid #20a2e3;
        box-shadow: 1px 1px 10px #888888;
        margin-left: 60px;
        
    }

    .repair-form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border-radius: 25px;
        border: solid #20a2e3;
        background-color: white;
        box-shadow: 1px 1px 10px #888888;
        margin-top: 50px;
        height: fit-content;
    }

    button {
        margin-top: 10px;
        font-weight: bolder;
        background-color: #5b6be8;
        width: 100%;
        border-radius: 25px;
        color: white;
        padding: 10px;
        cursor: pointer;
        transition: all 0.3s ease 0s;
    }

    button:hover {
        background-color: #3144d4;
        border-radius: 25px;
        color: white;
        border-color: #2c06ff;
        box-shadow: 0 0 15px #2c06ff;

    }

  body {
        background-color: #f2f2f2;
    }

    input {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    input:focus {
        outline: none;
        border-color: #2c06ff;
        box-shadow: 0 0 5px rgba(44, 6, 255, 0.5);
    }
</style>

<div class="add-repair-form">
    <div id="form-container">
        <div class="repair-form">
            <h2>Add Repair</h2>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="sku" value="{{ sku }}">
                <input type="hidden" name="lp" value="{{ lp }}">
                <div class="form-group">
                    <label for="repair">Repair:</label>
                    {{ form.repair }}
                </div>
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>

    <div id="iframe-container">
        <iframe src="https://product-imaging.intra.cityfurniture.io/products/skuinformation/{{ sku }}" width="100%" height="500px"></iframe>
    </div>
</div>

{% endblock %}

MDlogger/templates/MDlogger/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}MDlogger{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    
    <script>
        function confirmLogout() {
            if (confirm("Are you sure you want to log out?")) {
                window.location.href = "{% url 'MDlogger:logout' %}";
            }
        }
    </script>
    
</head>
<body style="background-color: aliceblue;">
    <style>
        .navbar {
            box-shadow: 2px 1px 15px #888888;
            padding-left: 20px;
        }

        .nav-link {
            border-radius: 25px;
            margin-right: 10px;
        }

        .nav-link:hover {
            font-weight: bold;
            color: white;
        }

        .navbar-nav .nav-item.dropdown:hover .dropdown-menu {
            display: block;
        }

        .dropdown-menu {
            border-radius: 6px;
            background-color: #2d3234ed;
            box-shadow: 2px 1px 15px #888888;
        }

        .dropdown-item {
            color: #ffffff;
        }

        .dropdown-item:hover {
            background-color: #20a2e3eb;
            font-weight: bold;
            color: white;
        }

        .pie-chart {
            width: 1em;
            height: 1em;
            border-radius: 50%;
            border: 1px solid #000000;
            background: conic-gradient(#f4f72f 0deg 60deg, #ff0000 60deg 210deg, #424bfc 180deg 360deg);
            display: inline-block;
            margin-left: 5px;
        }
    </style>
    
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #20a2e3;">
        <a class="navbar-brand text-white" href="{% url 'MDlogger:index' %}"><b>Major Damage System</b></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
            aria-expanded="false" aria-label="Toggle navigation" style="background-color: #45b8f2;">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Welcome, <i><b>{{ user.first_name }}</b></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'MDlogger:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'MDlogger:associate_home' %}">My Repairs</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Benchstock
                            <div class="pie-chart"></div>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'MDlogger:projects' %}">Projects</a>
                            <a class="dropdown-item" href="{% url 'MDlogger:dashboard' %}">Dashboard</a>
                            <a class="dropdown-item" href="{% url 'MDlogger:data' %}">Repaired Data</a>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#" onclick="confirmLogout()">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'MDlogger:index' %}">Login Required</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    
    <div class="container mt-4">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

MDlogger/templates/MDlogger/metrics.html
{% extends 'MDlogger/base.html' %}
{% block content %}
{% endblock %}

MDlogger/templates/MDlogger/projects.html
{% extends 'MDlogger/base.html' %}
{% block content %}

<style>
      #container {
        margin-top: 80px;
        display: flex;
        flex-direction: row;
        justify-content: space-around
        
    }

      #table-container {
        
        width: 100%;

    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
        margin-right: 350px;
        border: 2px solid black ;
        box-shadow: 1px 1px 10px #888888;  
    }


    th {
        background-color: #5b6be8;
        color: white;
        font-weight: bold;
        padding: 10px;
        text-align: left;
        border: 1px solid black;
    }

    th a {
        text-decoration: none;
        color: white;
    }

     td {
        border: 1px solid darkgray;
        padding: 8px;
        text-align: left;
        max-height: 100px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: wrap;
    
    }

    tr:nth-child(even) {
   background-color: #c4cacc;

    }

    tr:nth-child(odd) {
        background-color: #ffffff;
}
.project-form {
    max-width: 400px;
    
    padding: 25px;
    border-radius: 25px;
    border: solid #20a2e3;
    text-align: center;
    background-color: white;
    font-weight: bold;
    box-shadow: 1px 1px 10px 1px #888888;
    height: fit-content;
    margin-left: 50px;
}

button {
        display: inline-block;
        padding: 10px 20px;
        margin-top: 20px;
        font-weight: bold;
        background-color: #5b6be8;
        border: solid 2px black;
        border-radius: 25px;
        color: white;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        cursor: pointer;
        box-shadow: #888888 2px 0px 12px 0px;
        transition: all 0.4s ease 0s; 
    }

    button:hover {
        background-color: #3144d4;
        box-shadow: 0 0 15px #2c06ff;
        border-color: #2c06ff;
    }

    body {
        background-color: aliceblue;
        overflow: auto;
    }  

    input {
        width: 100%;
        padding: 5px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        
    }

    input:focus {
        outline: none;
        border-color: #2c06ff;
        box-shadow: 0 0 10px rgba(44, 6, 255, 0.5);
    }

    input:hover {
        background-color: #dfdfdf;
    }

    #id_description {
        height: 80px;  /* Adjust the height as needed */
    }
</style>
{% if user.is_authenticated %}
    <div id="container">
    <div id="table-container">
        <table id="projects-table">
            <tr>
                <th>Date</th>
                <th>Project Name</th>
                <th>Department</th>
                <th>Due By</th>
                <th>Assigned To</th>
                <th>Description</th>
                <th>Status</th>
            </tr>
            {% for project in projects %}
                <tr>
                    <td>{{ project.date|date:"m/d/Y" }}</td>
                    <td>{{ project.project }}</td>
                    <td>{{ project.department }}</td>
                    <td>{{ project.due|date:"m/d/Y" }}</td>
                    <td>{{ project.assignedto }}</td>
                    <td>{{ project.description }}</td>
                    <td>{{ project.status }}</td>
                </tr>
            {% endfor %}

        </table>
    </div>
    
    <form method="post" action="" class="project-form">
        {% csrf_token %}
        <label for="id_project">Project Name:</label><br>
        {{ form.project }} <br><br>
        <label for="id_department">Department:</label><br>
        {{ form.department }} <br><br>
        <label for="id_due">Due By:</label><br>
        <input type="date" id="id_due" name="due" required><br><br>
        <label for="id_assignedto">Assign To:</label><br>
        {{ form.assignedto }} <br><br>
        <label for="id_description" id="text-box">Project Description:</label><br>
        {{ form.description }} <br><br>
        <input type="hidden" name="status" value="Incomplete">
        <button type="submit">Create Project</button>
    </form>

    </div>
{% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'MDlogger/index.html' %}">Log In</a>
{% endif %}
{% endblock %}